name: GitHub Pages

on:
  push:
    branches:
    - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install xsltproc
    - run: xsltproc --param id "'https://$(basename $GITHUB_REPOSITORY)/'" --param updated "'$(date -u -Iseconds)'" style.xsl blog.xml
    - uses: actions/upload-pages-artifact@v3
      with:
        path: 'index.xml'
    - uses: actions/deploy-pages@v4
